[build]
builder = "NIXPACKS"
buildCommand = "npm install --legacy-peer-deps && npx prisma generate && npx next build"

[deploy]
startCommand = "mkdir -p /data && npx prisma db push && exec node_modules/.bin/next start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
